Application/EdFi.Ods.SandboxAdmin.Web/EdFi.Ods.SandboxAdmin.Web.nuspec, Application/EdFi.Ods.SwaggerUI/EdFi.Ods.SwaggerUI.nuspec, Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.nuspec
Fix for inculded all package files
=> [ODS-4237] Ed-Fi-Alliance repo paths in nuspec files

Application/Ed-Fi-Ods.sln
set the minimum version of visual studio to be 2017
=> [ODS-4246] Support for Visual Studio 2019

Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1
Updating CodeGen version to incorporate new implementation of GetHashCode and Equals methods on entity classes.
See also https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/45.
=> [ODS-4296] Primary key conflict due to case sensitivity

Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1, DatabaseTemplate/Scripts/EdFiMinimalTemplate.ps1, DatabaseTemplate/Scripts/GrandBend.ps1, DatabaseTemplate/Scripts/PostgreSqlMinimalTemplate.ps1, DatabaseTemplate/Scripts/PostgreSqlPopulatedTemplate.ps1
Paired with https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/100.
=> [ODS-3670] Remove composites API "hierarchical" feature

Application/EdFi.Ods.Api.IntegrationTestHarness/Options.cs, Application/EdFi.Ods.Api.IntegrationTestHarness/Startup.cs, Application/EdFi.Ods.Extensions.Homograph/Marker_EdFi_Ods_Extensions_Homograph.cs, Application/EdFi.Ods.Extensions.Sample/Marker_EdFi_Ods_Extensions_Sample.cs, Application/EdFi.Ods.Extensions.TPDM/Marker_EdFi_Ods_Extensions_TPDM.cs, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/Installers/OwnershipBasedAuthorizationInstaller.cs, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/Marker_EdFi_Ods_Features_OwnershipBasedAuthorization.cs, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/NHibernate/OwnershipBasedAuthorizationNHibernateConfigurationActivity.cs, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/OwnershipBasedAuthorizationConstants.cs, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/OwnershipBasedAuthorizationFeature.cs, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/Security/OwnershipInitializationCreateEntityDecorator.cs, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/SqlServer/OwnershipBasedAuthorizationDatabaseConstants.cs, Application/EdFi.Ods.Profiles.ExtensionsSample/Marker_EdFi_Ods_Profiles_ExtensionsSample.cs, Application/EdFi.Ods.SandboxAdmin.Web/App_Start/AuthConfig.cs, Application/EdFi.Ods.SandboxAdmin.Web/App_Start/BundleConfig.cs, Application/EdFi.Ods.SandboxAdmin.Web/App_Start/RazorGeneratorMvcStart.cs, Application/EdFi.Ods.SandboxAdmin.Web/App_Start/RouteConfig.cs, Application/EdFi.Ods.SandboxAdmin.Web/App_Start/WebApiConfig.cs, Application/EdFi.Ods.SandboxAdmin.Web/Content/Scripts/edfiadmin.auth.js, Application/EdFi.Ods.SandboxAdmin.Web/Content/Scripts/globals.js, Application/EdFi.Ods.SandboxAdmin.Web/Content/Scripts/sandbox.js, Application/EdFi.Ods.SandboxAdmin.Web/Content/Scripts/ss-validation.js, Application/EdFi.Ods.SandboxAdmin.Web/Filters/ExceptionHandlingFilter.cs, Application/EdFi.Ods.SandboxAdmin.Web/Filters/ExceptionLoggingFilter.cs, Application/EdFi.Ods.SandboxAdmin.Web/Properties/AssemblyInfo.cs, Application/EdFi.Ods.WebApi/Properties/AssemblyInfo.cs, Application/EdFi.Ods.WebApi/Startup/ApiStartup.cs, Application/EdFi.Ods.WebApi/Startup/AzureCloudOdsStartup.cs
Rebuilding working tree based on state of the code prior to the merge from master, with the changes done after reapplied on top.  Reverts all the line deletes mainly.
=> [ODS-4403] Reverting unintentional formatting changes

Application/EdFi.Ods.SwaggerUI/appsettings.json
remove urls to fix issue with iis deployment
=> [ODS-4401] Bring in Swashbuckle as a Replacement for swagger-ui

Scripts/NuGet/prep-installer-package.ps1
@stephenfuqua @vimayya @j-jordan
Please help review and merge the changes.
Thanks
https://tracker.ed-fi.org/browse/ODST-139
https://tracker.ed-fi.org/browse/ODS-4406
Accidently used wrong origin branch on PR - https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/pull/113
=> [ODST-139][ODS-4406] Update app common package version

Application/EdFi.Ods.WebApi/Web.Npgsql.config, Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1
See also https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/171
=> [ODS-4537] Support PostgreSQL "money" data type in API GetByExample requests

Application/EdFi.Ods.SandboxAdmin/Properties/launchSettings.json, Application/EdFi.Ods.SwaggerUI/Properties/launchSettings.json, Application/EdFi.Ods.WebApi/Properties/launchSettings.json, ReverseProxyTesting/README.md, ReverseProxyTesting/docker-compose.yml, ReverseProxyTesting/nginx.conf
Adding launch profiles to all three projects to support local reverse proxy testing.
=> [ODS-4449] Testing Reverse Proxy Support

logistics/scripts/modules/settings/settings-management.psm1, logistics/scripts/modules/utility/hashtable.psm1, logistics/scripts/modules/utility/hashtable.tests.ps1
tested with secret.json:
```json
{
"ApiSettings": {
"Features": [
{
"Name": "OpenApiMetadata",
"IsEnabled": true
},
{
"Name": "AggregateDependencies",
"IsEnabled": true
},
{
"Name": "TokenInfo",
"IsEnabled": true
},
{
"Name": "Extensions",
"IsEnabled": true
}
]
},
"Plugin": 
{
"Folder": "../../Plugin",
"Scripts": [ "tpdm" ]
}
}
```
=> [ODS-4681] Unable to override plugin setup on secret.json

Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1
Different usecase as below
Invoke-CodeGen -Engine SQLServer -IncludePlugins
Invoke-CodeGen -Engine SQLServer -IncludePlugins -ExtensionPaths @('C:\OSS-Workspace\Semalai_EndUser','C:\OSS-Workspace\EdFi.Ods.Extensions.TPDM')
Invoke-CodeGen -Engine SQLServer -ExtensionPaths @('C:\OSS-Workspace\Semalai_EndUser','C:\OSS-Workspace\EdFi.Ods.Extensions.TPDM')
Invoke-CodeGen -Engine SQLServer
Invoke-CodeGen -Engine SQLServer -IncludePlugins -ExtensionPaths @('C:\OSS-Workspace\Ed-Fi-Extensions\Extensions')
=> [ODS-4668] Code-gen for extension plugin creation 

Scripts/NuGet/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1, Scripts/NuGet/prep-installer-package.ps1
@vimayya @plioi @stephenfuqua 
Please help review and merge the changes.
Completed testing with: https://intedfitools1.msdf.org/buildConfiguration/OdsPlatform_OdsImplementationKotlin_Installers_WebApi/119394?buildTab=artifacts
=> [TSINSTALL-94] PART-2 Update App common version on WebApi, swagger and Sandbox admin installers 

Scripts/NuGet/prep-installer-package.ps1
@vimayya @plioi 
Please help review and merge the changes.
Updated web api, swagger and sandbox admin installers to use latest Appcommon package while building.
Thanks
=> [TSTINSTALL-105] Update AppCommon release version

Scripts/NuGet/EdFi.RestApi.Databases/Deployment.psm1
=> [ODS-4429]  Create Build to Promote Release Packages

logistics/scripts/configuration.packages.json
Updated package version for template databases.
=> [ODS-4847] Implement authorization support for OrganizationDepartment

logistics/scripts/configuration.packages.json
=> [ODS-4896] Upgrade log4net in DbDeploy

Scripts/NuGet/EdFi.Installer.SandboxAdmin/build-package.ps1, Scripts/NuGet/EdFi.Installer.SwaggerUI/build-package.ps1, Scripts/NuGet/EdFi.Installer.WebApi/build-package.ps1, Scripts/NuGet/prep-installer-package.ps1, logistics/scripts/configuration.packages.json
@vimayya 
Please help review the changes.
Thanks
=> [AA-1101] Move app common package details to configuration.packages.json for easy maintenance with other packages.

Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj, Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj
After this PR gets merged, I will regenerate the following packages:
- EdFi.Admin.DataAccess
- EdFi.LoadTools
- EdFi.Ods.Api
- EdFi.Ods.Common
- EdFi.Ods.Standard
- EdFi.Security.DataAccess
=> [ODS-5078] Update internal EdFi.Common package version

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj, Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj, Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj, logistics/scripts/configuration.packages.json
=> [ODS-5100] Use EdFi.Admin.DataAccess and EdFi.Security.DataAccess packages in ODS solution

configuration.packages.json
This Ed-Fi-ODS-Implementation PR based top of ODS-5223 to test and show all builds are green now 
Only Ed-Fi-Extensions Repo PR needs to be merged to Feature Branch after the review
=> [ODS-5231] Record Ownership Phase 2 - Update existing migration scripts to use new tables for Extension Projects 

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj, Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj, Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj
1 .GetApiClientIdentityAsync method calls GetClientAsync method in ClientAppRepo class
2 . SetSecret method calls GetClientByKey method in ClientAppRepo class
TryAuthenticateAsync method invoking database only one time now with _apiClientIdentityProvider.GetApiClientIdentityAsync(key);
=> ODS-5045 Optimize oauth/token request

configuration.packages.json
=> [ODS-4835] Code Generation for Resource Links to some Base Aggregates Fail

Application/EdFi.Ods.WebApi/Program.cs
Tested this code change required for Web Api calls for pgsql database
=> ODS-5247 Update Npgsql and HealthChecks libraries

LandingPage/index.css, LandingPage/index.html, LandingPage/index.js
Use : CTRL+F5 : to refresh the page by clearing GG chrome cache. So that it apply new CSS file for this change
=> ODS-5306 Caution note on the landing page

Application/EdFi.Ods.Features.OwnershipBasedAuthorization/Security/OwnershipInitializationCreateEntityDecorator.cs
See also: https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/461
=> [ODS-5276] Multiple authorization strategy support for single-item requests

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj, Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj, Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj
EdFi.Suite3.Admin.DataAccess package version Updated
=> ODS-5308 Clearing expired tokens in background could potentially allow access via expired tokens

DatabaseTemplate/Modules/create-database-template.psm1, configuration.packages.json, logistics/scripts/activities/build/create-database-package.ps1
Update package version numbers and allow for tracked_changes_xxx schemas instead of tracked_deletes_xxxx schemas.
=> [ODS-5382] Change Queries Enhancements for v5.3 to support Deletes and Key Changes using natural keys

configuration.packages.json
Package versions bump for TPDM templates.
=> [ODS-5456] Security Metadata - Resource Claim for people has wrong parent resource claim when TPDM extension is applied

Application/EdFi.Ods.Features.OwnershipBasedAuthorization/Security/OwnershipInitializationCreateEntityDecorator.cs
Added dependency on data management request context provider for ownership-based security.
=> [ODS-5505] Enhance Namespace-based authorization to support prefixed Namespaces

.github/workflows/edFi.ods.standard manual.yml
after doing package reference in SK project and it test that it's working fine
=> ODS-5572 EdFi.Suite3.Ods.Api & EdFi.Suite3.Ods.Standard nuget package is missing with package reference for dependencies

Application/EdFi.Ods.SandboxAdmin/Services/ClientCreator.cs, Application/EdFi.Ods.SandboxAdmin/appsettings.json
=> ODS-5592 maximum sandboxes in certification deployment

configuration.packages.json
https://intedfitools1.msdf.org/buildConfiguration/EdFi_SharedResources_OdsPlatformChangeQuery_OdsApi_Packages_EdFiOdsMinimalTemplateTpdmPostgreSQL?branch=&buildTypeTab=overview&mode=builds#all-projects  you can refer this build to verfiy each step from teamcity
=> ODS-5562 Move EdFi.Ods.Minimal.Template.TPDM.PostgreSQL Package build to Github Actions

configuration.packages.json
=> ODS-5564 Move EdFi.Ods.Populated.Template.TPDM.PostgreSQL Package build to Github Actions

DatabaseTemplate/Modules/create-database-bacpac.psm1, Scripts/NuGet/EdFi.Installer.SandboxAdmin/Install-EdFiOdsSandboxAdmin.psm1, Scripts/NuGet/EdFi.Installer.SandboxAdmin/test.ps1, Scripts/NuGet/EdFi.Installer.SwaggerUI/Install-EdFiOdsSwaggerUI.psm1, Scripts/NuGet/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1, Scripts/NuGet/EdFi.Installer.WebApi/test.ps1, Scripts/NuGet/EdFi.RestApi.Databases/PostDeploy.ps1, build.github.ps1, build.githubactions.ps1, configuration.packages.json, logistics/scripts/activities/build/CloudOds/PrepareDatabasesForExport.ps1, logistics/scripts/modules/database/database-management.psm1, logistics/scripts/modules/database/postgres-database-management.psm1, logistics/scripts/modules/packaging/create-package.psm1, logistics/scripts/modules/postgres-binaries/build-postgres-binaries.psm1
[PostgreSQL.Binaries Manually triggered build was failed in main branch due to previous PR change https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/pull/509/files#diff-68ff98f51f3b83fd39994a28b8c236e773f9ee4a0253ed34d14e500912c4eda8R95 
reference build 
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/actions/runs/3471367003/jobs/5800763462  . This PR this issue also fixed . you can see green now here https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/actions/runs/3471607393
=> [ODS-5381]Ensure that all PS scripts use forward slashes as directory separator

configuration.packages.json
This includes changes for handling min and max value range validation
=> ODS-5574 - Update to reference latest codegen

.github/workflows/Instl edFi.installer.sandboxAdmin manual.yml, .github/workflows/Instl edFi.installer.swaggerUI manual.yml, .github/workflows/Instl edFi.installer.webApi manual.yml, .github/workflows/Rebuild Database Templates.yml, .github/workflows/Trgr Trigger EdFi.Ods.DB.Templates workflow in ODS repo.yml
Note :Rebuild Database Templates workflow needs to update the latest all other reference workflow names after merging the PR since it's name change to workflow available only after merge to main.  That will happen in new PR
=>  ODS-5672 abbreviated prefixes Trgr & Instl Added

.github/workflows/CodeQL Security Scan.yml
Cron Job Schedule in Github Actions runs on UTC time ,so yesterday executed on 7 pm CST
=> ODS-5659 CodeQL Security Scan Cron Schedule updated

Application/run-sandbox.ps1
Simple script for starting WebApi, Swagger, and Sandbox Admin from the command line
=> [ODS-5685] Sandbox Startup Script

configuration.packages.json
Once ODS-5612 is merged, I will rebase this branch and target main in the PR
=> [ODS-5723] Clean Sample Profiles plugin

Application/EdFi.Ods.Api.IntegrationTestHarness/appsettings.json
Added configuration setting for Profile metadata expiration.
=> [ODS-5738] Introduce general-purpose caching interceptor and apply to Profiles metadata provider

configuration.packages.json
(This builds on the other PR opened by Semalai but is a deeper cleaning)
=> [ODS-5737] Clean up obsolete Profiles-related artifacts from solution

.github/CODEOWNERS
Initial codeowners file for the Ed-Fi-ODS-Implementation repository.
=> [ODS-5772] Codeowners file for ODS-Implementation

.github/workflows/Instl edFi.installer.sandboxAdmin manual.yml, .github/workflows/Instl edFi.installer.swaggerUI manual.yml, .github/workflows/Instl edFi.installer.webApi manual.yml, .github/workflows/PostgreSQL.Binaries manual .yml, .github/workflows/Publish to Azure Artifacts.yml, .github/workflows/Rebuild Database Templates.yml
Check for Azure and Github secret on Ed-Fi repositories, but skip steps that use those secrets in non-Ed-Fi repositories.
=> [ODS-5775] Github actions in forked repositories

logistics/scripts/activities/build/create-database-package.ps1
Builds are passing now
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/actions/runs/4683667133
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/actions/runs/4683868293
=> [ODS-5796] Modify builds to support multiple standard versions

Extensions/Sample/SampleMetaEd/Common/Pet.metaed, configuration.packages.json
{{ApiBaseUrl}}/data/v3/ed-fi/staffs
Request Json
{
"staffUniqueId": "{{supplied:staffUniqueId}}",
"firstName": "John",
"lastSurname": "Doe",
"_ext": {
"Sample": {
"firstOwnedPetDate": "2000-01-01",
"pets": [
{
"petName": "Re",
"isFixed": false
}
],
"petPreference": {
"minimumWeight": 20,
"maximumWeight": 35
}
}
}
}
**
**
=> [ODS-5755] API validation for string min/max

.github/workflows/InitDev,Unit tests,Integration tests,Package.yml, .github/workflows/InitDev,Unit tests,Integration tests,Smoke Tests using Sandbox, Year-Specific and Shared Instance.yml, .github/workflows/Instl edFi.installer.sandboxAdmin manual.yml, .github/workflows/Instl edFi.installer.swaggerUI manual.yml, .github/workflows/Instl edFi.installer.webApi manual.yml
Once every thing is good , finally I will remove teamcity builds after this PR merge
=> [ODS-5819] windows-latest build updated to powershell 5.1

.github/workflows/Publish to Azure Artifacts.yml
https://github.com/ahmadnassri/action-workflow-run-wait/blob/master/README.md
=> [ODS-5915] Adding timeout and delay to action-workflow-run-wait action

Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1, logistics/scripts/modules/settings/settings-management.psm1, logistics/scripts/modules/utility/key-management.psm1
=> [ODS-5913] Encrypt connection strings in Admin database

docker/ods-api-web-api/alpine/mssql/appsettings.template.json, docker/ods-api-web-api/alpine/pgsql/appsettings.template.json
Add a Contact person type cache suppression setting and an encryption key placeholder setting for Docker Web API.
=> [ODS-5898] Add missing settings placeholders for Web API Docker 

Application/Ed-Fi-Ods.sln, Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj, Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj, Application/EdFi.Ods.SwaggerUI/EdFi.Ods.SwaggerUI.csproj, Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj, NOTICES.md, configuration.packages.json
Updated NOTICES.md file
Removed unused references
=> [ODS-5754] Update License Notices and Cleanup Unsued References

configuration.packages.json
To Fix tpdm description tpdm core and version 1.1.0
=> [ODS-5884] EdFi.Suite3.Ods.Extensions.TPDM.Core package version updated

logistics/scripts/modules/utility/xml-validation.psm1
These changes come from a snippet shared by @gmcelhanon
=> [ODS-5927] Database template builds should error on XML validation failures

DatabaseTemplate/Modules/database-template-source.psm1, DatabaseTemplate/Scripts/Northridge.ps1, logistics/scripts/modules/database/database-lifecycle.psm1
Testing Steps
1. Check out 7.0 Tag in your local as branch for ODS & ODS Implementation Branch
2. Update code in this ticket PR
3. Update ApiSettings:PopulatedTemplateScript" "Northridge" as below
C:\Ed-Fi-ODS-Implementation\Application\EdFi.Ods.WebApi\> dotnet user-secrets set "ApiSettings:PopulatedTemplateScript" "Northridge"
4 . In a PowerShell session navigate to <source directory>\Ed-Fi-ODS-Implementation\.
Execute .\Initialize-PowershellForDevelopment.ps1.
5 . Run Install-DbDeploy
6 . Execute Reset-PopulatedTemplate.
7. Finally verify in database for record count and Northridge ISD
SELECT * from EdFi_Ods_Populated_Template.edfi.Student
SELECT * from EdFi_Ods_Populated_Template.edfi.EducationOrganization
SELECT count from EdFi_Ods_Populated_Template.edfi.Student …
=> [ODS-6035] Northridge SQL Server 7.0 Migration

logistics/scripts/modules/database/postgres-database-management.psm1
Tested successfully in PS 5.1 and 7.3.4
Gihtub is not planning to provide support for PS 7.3 https://github.com/actions/runner-images/issues/7242#issuecomment-1456346084
=> [ODS-5656] Postgres-database-management.psm1 doesn't work in PowerShell 7.3

Docker/ods-api-db-admin/alpine/pgsql/Dockerfile, Docker/ods-api-db-ods-minimal/alpine/pgsql/Dockerfile, Docker/ods-api-db-ods-sandbox/alpine/pgsql/Dockerfile, Docker/ods-api-swaggerui/alpine/Dockerfile, Docker/ods-api-web-api/alpine/mssql/Dockerfile, Docker/ods-api-web-api/alpine/pgsql/Dockerfile, Docker/ods-api-web-sandbox-admin/alpine/mssql/Dockerfile, Docker/ods-api-web-sandbox-admin/alpine/pgsql/Dockerfile
To test locally, go to Docker folder
Run `./get-versions.ps1 -prerelease`
Then run `./build-images.ps1 -prerelease`
=> [ODS-6099] Update alpine and postgres hash in Docker

configuration.packages.json
=> [ODS-6098] Read profile Content Type is wrong in swagger 

DatabaseTemplate/Modules/database-template-source.psm1, logistics/scripts/modules/plugin/plugin-source.psm1
Test for both standard versions
=> [ODS-6086] Improve volatility of DatabaseViews.generated.json

configuration.packages.json
=> [ODS-6084] Remove XML Lookup Utility

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj, Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj, Application/EdFi.Ods.SwaggerUI/EdFi.Ods.SwaggerUI.csproj, Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj, configuration.packages.json
Package published EdFi.Suite3.Ods.SandboxAdmin.5.3.1490.nupkg
EdFi.Suite3.Ods.SwaggerUI.5.3.1490.nupkg
EdFi.Suite3.Ods.WebApi.5.3.1490.nupkg
EdFi.Suite3.Ods.WebApi.Prerelease.5.3.1490.nupkg
EdFi.Suite3.RestApi.Databases.5.3.1490.nupkg
=> [ODS-6093] 5.3-cqe Update package dependencies to avoid security vulnerabilities

configuration.packages.json
All packages have been updated
=> [ODS-6116] DbDeploy update was not tracked in ODS API

.github/workflows/CodeQL Security Scan.yml, .github/workflows/Dependencies Security Scan.yml, .github/workflows/InitDev (Postgres), Tests using Sandbox, Year-Specific and Shared Instance.yml, .github/workflows/InitDev (Postgres),Unit tests,Integration tests.yml, .github/workflows/InitDev,Unit tests,Integration tests,Package.yml, .github/workflows/InitDev,Unit tests,Integration tests,Smoke Tests using Sandbox, Year-Specific and Shared Instance.yml, .github/workflows/Publish to Azure Artifacts.yml, .github/workflows/Trigger EdFi.Ods.DB.Templates workflow in ODS repo.yml, .github/workflows/edFi.ods.standard pullrequest.yml, Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj, Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj, Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj, configuration.packages.json, logistics/scripts/modules/database/database-management.psm1, logistics/scripts/modules/settings/settings-management.psm1
Reference :https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/pull/645
Reference https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.Common/overview/6.1.33
=> [ODS-6188] Upgrade System.Data.SqlClient upgrade dependency v6.1-patch3 Patch Release

configuration.packages.json
I didn't know about this file until today, and thus missed these updates on previous tickets.
=> [ODS-6169] Update some package dependencies

Application/Ed-Fi-Ods.sln.DotSettings, Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj, Application/EdFi.Ods.Api.IntegrationTestHarness/PostmanSecurityMetadataInitializer.cs, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj, Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj, Application/EdFi.Ods.SandboxAdmin/Services/SecurityService.cs, Application/EdFi.Ods.SandboxAdmin/Services/SqlServerTemplateDatabaseLeaQuery.cs, Application/EdFi.Ods.SandboxAdmin/Startup.cs, Application/EdFi.Ods.SwaggerUI/EdFi.Ods.SwaggerUI.csproj, Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj, configuration.packages.json, logistics/scripts/modules/settings/settings-management.psm1
1. upgrade to net8
2. upgrade packages and fix deprecated code
3. change system.data.sqlclient to Microsoft.Data.SqlClient
4. change EF to EFC
=> [ODS-6167] Migrate Ed-Fi-Ods Solution to .Net 8 (Implementation)

Docker/ods-api-db-admin/alpine/pgsql/Dockerfile, Docker/ods-api-db-ods-minimal/alpine/pgsql/Dockerfile, Docker/ods-api-db-ods-sandbox/alpine/pgsql/Dockerfile, Docker/ods-api-swaggerui/alpine/Dockerfile, Docker/ods-api-web-api/alpine/mssql/Dockerfile, Docker/ods-api-web-api/alpine/pgsql/Dockerfile, Docker/ods-api-web-api/alpine/pgsql/run.sh, Docker/ods-api-web-sandbox-admin/alpine/mssql/Dockerfile, Docker/ods-api-web-sandbox-admin/alpine/pgsql/Dockerfile, Docker/ods-api-web-sandbox-admin/alpine/pgsql/run.sh
To test, run
```powershell
cd Docker
./get-versions.ps1 -StandardVersion 5.0.0 -ExtensionVersion 1.1.0 -PreRelease
docker compose -f ./docker-compose-sandbox.yml up -d --build
```
=> [ODS-5778] Change Docker check to see if PostgreSQL is ready

.github/workflows/InitDev (Postgres), Tests using Sandbox, Year-Specific and Shared Instance.yml, .github/workflows/InitDev,Unit tests,Integration tests,Smoke Tests using Sandbox, Year-Specific and Shared Instance.yml, configuration.packages.json
Include changes on yml files: net6 to net8
=> [ODS-6262] Cherry-Pick ODS-5686 into main6x - Minimal template should include only include descriptors 

logistics/scripts/modules/database/database-management.psm1, logistics/scripts/modules/settings/settings-management.psm1
* SqlServer  Install module updated to specific version 21.1.18256
* Added Debugging Code
* Install-Module -Name SqlServer -RequiredVersion "21.1.18256" updated
* Option 2 with 'Encrypt'='False' for master Connection String
* Encrypt false flag added
* Added only for Sqlserver
* Cleanup codefix
=> [ODS-6287] Fix broken builds due to SQLServer Module update v5.4 (#645)

.github/workflows/InitDev Postgres, Smoke Tests.yml, .github/workflows/InitDev Postgres, Unit tests, Integration tests.yml, .github/workflows/InitDev, Smoke Tests.yml, .github/workflows/InitDev, Unit tests, Integration tests, Package.yml, .github/workflows/PostgreSQL.Binaries manual .yml, .github/workflows/Promote Packages.yml, .github/workflows/Publish to Azure Artifacts.yml, .github/workflows/edFi.ods.standard manual.yml, .github/workflows/edFi.ods.standard pullrequest.yml, Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1, build.github.ps1, build.githubactions.ps1, logistics/scripts/Invoke-SdkGen.ps1
=> [ODS-6271] Cherry-Pick ODS-6153 main6x - Migrate SdkGen to target .NET 8

configuration.packages.json, logistics/scripts/modules/database/database-management.psm1
I executed Database templates builds to make sure new code is working fine with all template builds
=> [ODS-4053] Refactor database-management.psm1 use of `trap`

DatabaseTemplate/Scripts/Northridge.ps1
Testing Steps
1. Check out 7.1 Tag in your local as branch for ODS & ODS Implementation Branch
2. Update code in this ticket PR
3. Update ApiSettings:PopulatedTemplateScript" "Northridge" as below
C:\Ed-Fi-ODS-Implementation\Application\EdFi.Ods.WebApi\> dotnet user-secrets set "ApiSettings:PopulatedTemplateScript" "Northridge"
4 . In a PowerShell session navigate to <source directory>\Ed-Fi-ODS-Implementation\.
Execute .\Initialize-PowershellForDevelopment.ps1.
5 . Run Install-DbDeploy
6 . Execute Reset-PopulatedTemplate.
7. Finally verify in database for record count and Northridge ISD
SELECT * from EdFi_Ods_Populated_Template.edfi.Student
SELECT * from EdFi_Ods_Populated_Template.edfi.EducationOrganization
SELECT count from EdFi_Ods_Populated_Template.edfi.Student …
=> [ODS-6036] Northridge SQL Server 7.1 Migration

.github/workflows/InitDev Postgres, MultiTenancy.yml, .github/workflows/InitDev Postgres, Smoke Tests.yml, .github/workflows/InitDev Postgres, Unit tests, Integration tests.yml, .github/workflows/InitDev, MultiTenancy.yml, .github/workflows/InitDev, Smoke Tests.yml, .github/workflows/InitDev, Unit tests, Integration tests, Package.yml, .github/workflows/Instl edFi.installer.sandboxAdmin manual.yml, .github/workflows/Instl edFi.installer.swaggerUI manual.yml, .github/workflows/Instl edFi.installer.webApi manual.yml, .github/workflows/PostgreSQL.Binaries manual .yml, .github/workflows/Rebuild Database Templates.yml
=> [ODS-6356]  Github Action build warning

.github/workflows/Publish to Docker Hub.yml
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/actions/runs/9616884424
=> [ODS-6390] Pulling Standard Version  5.0.0

InstallerPackages/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1
Summary of Changes:
- Remove UseAlternateUserName WebApi installer parameter
- Add a new CreateSqlLogin WebApi installer parameter with a note regarding database server administrator rights used by the created login
=> [ODS-4936] Installer support and Integrated Security 

.github/workflows/InitDev (Postgres), Tests using Sandbox, Year-Specific and Shared Instance.yml, .github/workflows/InitDev (Postgres),Unit tests,Integration tests.yml, .github/workflows/InitDev,Unit tests,Integration tests,Package.yml, .github/workflows/InitDev,Unit tests,Integration tests,Smoke Tests using Sandbox, Year-Specific and Shared Instance.yml, Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1, build.github.ps1, logistics/scripts/Invoke-SdkGen.ps1
Summary of Changes:
- Add Java path parameter to PowerShell scripts
- Update GitHub actions to pass the correct Java path during builds
=> [ODS-6227] Migrate SdkGen to target .NET 8 (5.x) 

configuration.packages.json, logistics/scripts/Invoke-SdkGen.ps1
Changes included in this PR:
- Re-generated the DB templates and referenced them
- Fixed an issue during TestSdk generation that prevented `All` namespace from being included.
=> [ODS-6290][ODS-6227] Pre release tasks for ODS/API 5.4

.github/workflows/Instl edFi.installer.sandboxAdmin manual.yml, .github/workflows/Instl edFi.installer.swaggerUI manual.yml, .github/workflows/Instl edFi.installer.webApi manual.yml, Scripts/NuGet/EdFi.Installer.SandboxAdmin/EdFi.Installer.SandboxAdmin.nuspec, Scripts/NuGet/EdFi.Installer.SandboxAdmin/Install-EdFiOdsSandboxAdmin.psm1, Scripts/NuGet/EdFi.Installer.SandboxAdmin/build-package.ps1, Scripts/NuGet/EdFi.Installer.SwaggerUI/EdFi.Installer.SwaggerUI.nuspec, Scripts/NuGet/EdFi.Installer.SwaggerUI/Install-EdFiOdsSwaggerUI.psm1, Scripts/NuGet/EdFi.Installer.SwaggerUI/build-package.ps1, Scripts/NuGet/EdFi.Installer.WebApi/EdFi.Installer.WebApi.nuspec, Scripts/NuGet/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1, Scripts/NuGet/EdFi.Installer.WebApi/build-package.ps1, Scripts/NuGet/EdFi.Installer.WebApi/test.ps1
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Installer.WebApi/overview/5.4.53
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Installer.SwaggerUI/overview/5.4.55
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Installer.SandboxAdmin/overview/5.4.55
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.RestApi.Databases/overview/5.4.2243
=> [.ODS-6233] EdFi.Suite3.Installer.WebApi EdFi.Suite3.Installer.SwaggerUI EdFi.Suite3.Installer.SandboxAdmin Workflow Added

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj, Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj, Application/EdFi.Ods.SandboxAdmin.Services/EdFi.Ods.SandboxAdmin.Services.csproj, Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj, Application/EdFi.Ods.SwaggerUI/EdFi.Ods.SwaggerUI.csproj, Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj, Docker/ods-api-bulk-load-console/alpine/Dockerfile, Docker/ods-api-db-admin/alpine/pgsql/Dockerfile, Docker/ods-api-db-ods-minimal/alpine/pgsql/Dockerfile, Docker/ods-api-db-ods-sandbox/alpine/pgsql/Dockerfile, Docker/ods-api-swaggerui/alpine/Dockerfile, Docker/ods-api-web-api/alpine/mssql/Dockerfile, Docker/ods-api-web-api/alpine/pgsql/Dockerfile, Docker/ods-api-web-sandbox-admin/alpine/mssql/Dockerfile, Docker/ods-api-web-sandbox-admin/alpine/pgsql/Dockerfile, configuration.packages.json
Postgres image vulnerability points to the gosu package; the vulnerability affects specific functionality in the Go language that does not affect the gosu package as per this [statement](https://github.com/tianon/gosu/issues/136)
=> [ODS-6406] Fix code vulnerabilities

Application/EdFi.Ods.SwaggerUI/Resources/Swashbuckle_index.html
* Adds a new SwaggerUI plugin, which, if route-context values are in use, dynamically updates the token URL to match the user's currently selected route context value each time the authenticate dialog is opened.
=> [ODS-6410] Swagger UI v7.2 is not updating Token URL

configuration.packages.json
=> [ODS-6538-5x] Configuration packages updated for v5.4-patch1

DatabaseTemplate/Scripts/Northridge.ps1
Testing Steps
Check out 7.3 Tag in your local as branch for ODS & ODS Implementation Branch
Update code in this ticket PR
Update ApiSettings:PopulatedTemplateScript" "Northridge" as below
C:\Ed-Fi-ODS-Implementation\Application\EdFi.Ods.WebApi> dotnet user-secrets set "ApiSettings:PopulatedTemplateScript" "Northridge"
4 . In a PowerShell session navigate to \Ed-Fi-ODS-Implementation.
Execute .\Initialize-PowershellForDevelopment.ps1.
5 . Run  InitDev  
6 . Install-DbDeploy
7 . Execute Reset-PopulatedTemplate.
Finally verify in database for record count and Northridge ISD
SELECT * from EdFi_Ods_Populated_Template.edfi.Student
SELECT * from EdFi_Ods_Populated_Template.edfi.EducationOrganization
SELECT count from EdFi_Ods_Populated_Template.edfi.Student
SELECT count from …
=> [ODS-6472] Northridge SQL Server 7.3 Migration

DatabaseTemplate/Scripts/NorthridgePostgreSql.ps1
Refer this ticket https://edfi.atlassian.net/browse/ODS-6473  comments for testing steps
=> [ODS-6495] Northridge PostgreSQL 7.3 Migration

.github/workflows/Cleanup Caches by a branch.yml, .github/workflows/CodeQL Security Scan.yml, .github/workflows/Dependencies Security Scan.yml, .github/workflows/Docker Test.yml, .github/workflows/InitDev Postgres, MultiTenancy.yml, .github/workflows/InitDev Postgres, Smoke Tests.yml, .github/workflows/InitDev Postgres, Unit tests, Integration tests.yml, .github/workflows/InitDev, Unit tests, Integration tests, Package.yml, .github/workflows/Promote Packages.yml, .github/workflows/Publish to Azure Artifacts.yml, .github/workflows/Publish to Docker Hub.yml, configuration.packages.json
v7.2-patch1
edfi.ods.common
edfi.ods.standard
edfi.ods.api
edfi.ods.webapi
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.WebApi.Standard.4.0.0/overview/7.2.2539
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.Api/overview/7.2.897
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.Common/overview/7.2.905
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.Api/overview/7.2.897
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.Standard.4.0.0/overview/7.2.878
=> [ODS-6481] 7.2 Patch Release for Nhibernate Upgrade

Application/EdFi.Ods.SwaggerUI/SwaggerStartupBase.cs, Application/EdFi.Ods.SwaggerUI/wwwroot/index.css, Application/EdFi.Ods.SwaggerUI/wwwroot/index.html, Application/EdFi.Ods.SwaggerUI/wwwroot/index.js
Add Appsettings value to EdFiAzureSwaggerUIDisclaimerContent variable for testing in your local machine 
This interactive documentation and demo are for demonstration purposes only.<br />
These sandboxes are not intended for testing integration, and care must be taken not to use real student data.
=> [ODS-6451] EdFiAzure SwaggerUI Disclaimer Content Added

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj, Application/EdFi.Ods.Api.IntegrationTestHarness/Migrations/MultiTenantSecurityDatabaseConnectionStringCatalog.cs, Application/EdFi.Ods.Api.IntegrationTestHarness/UpdateAdminDatabaseStartupCommand.cs
=> [ODS-6602] API only allows tenant1's profiles when different profiles are set up for different tenants

.github/workflows/InitDev, Unit tests, Integration tests, Package.yml, configuration.packages.json
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.Common/overview/7.2.954
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.WebApi.Standard.5.1.0/overview/7.2.2682
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.Api/overview/7.2.944
=> [ODS-6615] v7.2-patch2 release 

.github/workflows/InitDev, Unit tests, Integration tests, Package.yml, configuration.packages.json
v7.3-patch1 release packages
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.Common/overview/7.3.553
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.Api/overview/7.3.545
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Ods.WebApi.Standard.5.2.0/overview/7.3.1574
=> [ODS-6626] v7.3-patch1 release Package upgrade

Docker/ods-api-bulk-load-console/alpine/Dockerfile, Docker/ods-api-db-admin/alpine/pgsql/Dockerfile, Docker/ods-api-db-ods-minimal/alpine/pgsql/Dockerfile, Docker/ods-api-db-ods-sandbox/alpine/pgsql/Dockerfile
https://pkgs.alpinelinux.org/packages?page=1&name=openssl&branch=edge&repo=&arch=x86_64&origin=&maintainer=&flagged=
Check here for
=> [ODS-6626] v7.3-patch1 release -Docker openssl upgrade

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj, Application/EdFi.Ods.SandboxAdmin.Services/Models/Application/ApplicationCreateModel.cs, Application/EdFi.Ods.SandboxAdmin.Services/Models/Application/ApplicationIndexViewModel.cs, Application/EdFi.Ods.SandboxAdmin.Services/Models/Vendor/VendorCreateModel.cs, Application/EdFi.Ods.SandboxAdmin/Controllers/Api/ApplicationController.cs, Application/EdFi.Ods.SandboxAdmin/Controllers/Api/VendorController.cs, Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj, Application/EdFi.Ods.SandboxAdmin/Views/Application/Index.cshtml, Application/EdFi.Ods.SandboxAdmin/Views/Vendor/Index.cshtml, Application/EdFi.Ods.SandboxAdmin/wwwroot/js/application.js, Application/EdFi.Ods.SandboxAdmin/wwwroot/js/vendor.js, Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj
=> [ODS-6639] Sandbox Admin for Certification Testing

Extensions/4.0.0/Sample/SampleMetaEd/DomainEntity/BusRoute.metaed, Extensions/Sample/SampleMetaEd/DomainEntity/BusRoute.metaed, configuration.packages.json
Removes redundant Id property, and uses BusReference instead
=> [DMS-610] Update Sample.BusReference Entity

.github/workflows/CodeQL Security Scan.yml, .github/workflows/InitDev Postgres, MultiTenancy.yml, .github/workflows/InitDev Postgres, Smoke Tests.yml, .github/workflows/InitDev Postgres, Unit tests, Integration tests.yml, .github/workflows/InitDev, MultiTenancy.yml, .github/workflows/InitDev, Smoke Tests.yml, .github/workflows/InitDev, Unit tests, Integration tests, Package.yml, .github/workflows/Rebuild Database Templates.yml, configuration.packages.json
Merge this PR with a Squash and Merge.
NOTE: This branch contains cumulative commits for [ODS-6675](https://edfi.atlassian.net/browse/ODS-6675), [ODS-6681](https://edfi.atlassian.net/browse/ODS-6681) and [ODS-6682](https://edfi.atlassian.net/browse/ODS-6682).
[ODS-6675]: https://edfi.atlassian.net/browse/ODS-6675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ODS-6681]: https://edfi.atlassian.net/browse/ODS-6681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ODS-6682]: https://edfi.atlassian.net/browse/ODS-6682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ODS-6682] Resource child item references that have key unification result in unresolvable links
