Application/EdFi.Ods.WebApi/Web.Base.config

This PR implements configuration file-based cache expiration settings for the Descriptors cache and Person UniqueId/USI cache.
See also https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/44

[ODS-4046] Recreating student, staff or parent after deletion returns 400 Bad Request

---

Application/EdFi.Ods.Extensions.Homograph/Artifacts/Metadata/ApiModel-EXTENSION.json
Application/EdFi.Ods.Extensions.Sample/Artifacts/Metadata/ApiModel-EXTENSION.json
Application/EdFi.Ods.Extensions.Sample/Artifacts/Schemas/EXTENSION-Ed-Fi-Extended-Core.xsd
Application/EdFi.Ods.Extensions.Sample/Artifacts/Schemas/EXTENSION-Interchange-Descriptors-Extension.xsd
Application/EdFi.Ods.Extensions.Sample/Artifacts/Schemas/EXTENSION-Interchange-EducationOrganization-Extension.xsd
Application/EdFi.Ods.Extensions.Sample/Artifacts/Schemas/EXTENSION-Interchange-Parent-Extension.xsd
Application/EdFi.Ods.Extensions.Sample/Artifacts/Schemas/EXTENSION-Interchange-StaffAssociation-Extension.xsd
Application/EdFi.Ods.Extensions.Sample/Artifacts/Schemas/EXTENSION-Interchange-Student-Extension.xsd
Application/EdFi.Ods.Extensions.Sample/Artifacts/Schemas/EXTENSION-Interchange-StudentEnrollment-Extension.xsd
Application/EdFi.Ods.Extensions.Sample/Artifacts/Schemas/EXTENSION-Interchange-StudentProgram-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Ed-Fi-Extended-Core.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-AssessmentMetadata-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-Descriptors-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-EducationOrganization-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-PK12StudentData-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-PerformanceEvaluation-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-ProfessionalDevelopment-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-RecruitmentAndStaffing-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-StaffAssociation-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-StudentEnrollment-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-StudentGradebook-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-Survey-Extension.xsd
Application/EdFi.Ods.Extensions.TPDM/Artifacts/Schemas/EXTENSION-Interchange-TeacherCandidate-Extension.xsd

Updates Core and Extensions based on MetaEd v2.2.1-dev.7, which includes bumping to v5.0.0 and removing the copyright header from the xsds.

[ODS-4370] Bring in MetaEd artifacts for release version change

---

logistics/scripts/modules/tools/ToolsHelper.psm1

Looking to get feedback on the following change to ensure that the correct tools path is being used for DbDeploy tool.
**Background**
The AdminApp Installer uses the Invoke-DbDeploy function from logistics/scripts/modules/tools/ToolsHelper.psm1 in the Invoke-DbUpScripts function. Following is the snippet where it is used:
```
function Invoke-DbUpScripts {
[CmdletBinding()]
param (
[hashtable]
[Parameter(Mandatory=$true)]
$Config
)
Invoke-Task -Name ($MyInvocation.MyCommand.Name) -Task {
$adminConnectionString = Get-AdminInstallConnectionString $Config
$engine = "PostgreSql"
if(!(Test-IsPostgreSQL -Engine $Config.engine)){
$engine = "SqlServer"
}
$params = @{
Verb = "Deploy"
Engine = $engine
Database = "Admin"
ConnectionString = $adminConnectionString
FilePaths = $Config.WebApplicationPath …
```

[AA-977] Admin App Installer should use ToolsPath parameter to reference tools

---

DatabaseTemplate/Scripts/EdFiMinimalTemplate.ps1
DatabaseTemplate/Scripts/GrandBend.ps1
DatabaseTemplate/Scripts/PostgreSqlMinimalTemplate.ps1
DatabaseTemplate/Scripts/PostgreSqlPopulatedTemplate.ps1

Updating package references for the authorization view changes to prevent duplicates from staff employment and assignments.
See also:
- https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/234
- https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-Extensions/pull/4

[ODS-4592] Duplicates from Security Views

---

logistics/scripts/configuration.packages.json

Main builds are failing now  after Merge of ODS-4028 eventhough I had all green build at the time of merge. 
I am again updating the template builds to fix the build issues  .

[ODS-4828] Sample data updates for 3.3.0-a 

---

Application/EdFi.Ods.WebApi/log4net.config
Scripts/NuGet/EdFi.Installer.SandboxAdmin/Install-EdFiOdsSandboxAdmin.psm1
Scripts/NuGet/EdFi.Installer.SandboxAdmin/test.ps1
Scripts/NuGet/EdFi.Installer.SwaggerUI/Install-EdFiOdsSwaggerUI.psm1
Scripts/NuGet/EdFi.Installer.SwaggerUI/test.ps1
Scripts/NuGet/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1
Scripts/NuGet/EdFi.Installer.WebApi/test.ps1
Scripts/NuGet/prep-installer-package.ps1
logistics/scripts/modules/packaging/nuget-helper.psm1

$parameters = @{
DbConnectionInfo = @{
Engine="SqlServer"
Server="localhost"
UseIntegratedSecurity=$true
}
InstallType = "Sandbox"
WebApiFeatures = @{
BearerTokenTimeoutMinutes="BearerTokenTimeoutMinutes"                                  
ExcludedExtensionSources="GrandBend"
Features= @{
"changeQueries"= @{
Name= "changeQueries"
IsEnabled= $true
}
"OpenApiMetadata"= @{
Name= "OpenApiMetadata"
IsEnabled= $false
}
"composites"= @{
Name= "composites"
IsEnabled= $false
}
"profiles"= @{
Name= "profiles"
IsEnabled= $false
}
"identityManagement"= @{
Name= "identityManagement"
IsEnabled= $false
}
"extensions"= @{
Name= "extensions"
IsEnabled= $false
}
"ownershipBasedAuthorization"= @{
Name= "ownershipBasedAuthorization"
IsEnabled= $false
}
"uniqueIdValidation"= @{
Name= "uniqueIdValidation" …

[ODS-4871] Update Installers/NugetHelper to load release promoted packages by default

---

Scripts/NuGet/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1

$parameters = @{
DbConnectionInfo = @{
Engine="SqlServer"
Server="localhost"
UseIntegratedSecurity=$true
}
InstallType = "Sandbox"
WebApiFeatures = @{
BearerTokenTimeoutMinutes="BearerTokenTimeoutMinutes"                                   
ExcludedExtensionSources="GrandBend"
Features= @(
@{
Name= "changeQueries"
IsEnabled= $true
},
@{
Name= "OpenApiMetadata"
IsEnabled= $true
},
@{
Name= "composites"
IsEnabled= $true
},
@{
Name= "profiles"
IsEnabled= $true
},
@{
Name= "identityManagement"
IsEnabled= $true
},
@{
Name= "extensions"
IsEnabled= $true
},
@{
Name= "ownershipBasedAuthorization"
IsEnabled= $true
},
@{
Name= "uniqueIdValidation"
IsEnabled= $true
}
)
}      
}

[ODS-4874] WebAPI installer does not enable any features 

---

Scripts/NuGet/.gitignore
Scripts/NuGet/EdFi.Installer.SandboxAdmin/EdFi.Installer.SandboxAdmin.nuspec
Scripts/NuGet/EdFi.Installer.SandboxAdmin/Install-EdFiOdsSandboxAdmin.psm1
Scripts/NuGet/EdFi.Installer.SandboxAdmin/build-package.ps1
Scripts/NuGet/EdFi.Installer.SwaggerUI/EdFi.Installer.SwaggerUI.nuspec
Scripts/NuGet/EdFi.Installer.SwaggerUI/Install-EdFiOdsSwaggerUI.psm1
Scripts/NuGet/EdFi.Installer.SwaggerUI/build-package.ps1
Scripts/NuGet/EdFi.Installer.WebApi/EdFi.Installer.WebApi.nuspec
Scripts/NuGet/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1
Scripts/NuGet/EdFi.Installer.WebApi/build-package.ps1
Scripts/NuGet/prep-installer-package.ps1

@vimayya @stephenfuqua @saa14 
Please help review the changes.
1. Updated installers to use common modules (hashtable. psm1, nuget-helper.psm1, TaskHelper.psm1, ToolsHelper.psm1) from AppCommon package.
2. Refactored all the module paths.
3. Added AppCommonVersion parameter on build-package to have value at the build time
4. Using prerelease version of AppCommon, will be updating to release version
Blocked by: https://github.com/Ed-Fi-Alliance/Ed-Fi-ODS-Deploy/pull/215/files
Thanks

[AA-1101] Updated installers to use common modules from AppCommon package and team city update to build platform packages with latest app common

---

Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj
Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj

Upgraded to 5.3.1v all projects that reference EdFi.Suite3.Common
After the PR is merged, I will check if the following packages need to be re-generated through TeamCity:
- EdFi.Admin.DataAccess
- EdFi.Common
- EdFi.LoadTools
- EdFi.Ods.Api
- EdFi.Ods.Common
- EdFi.Ods.Standard
- EdFi.Security.DataAccess

[ODS-5078] Update internal EdFi.Common package version

---

Scripts/NuGet/EdFi.Installer.SandboxAdmin/Install-EdFiOdsSandboxAdmin.psm1

The TPDM namespace was missing from the function in the installer that generates the default appsettings, so when the Sandbox Admin was installed, this namespace was missing. Now this namespace has been added as part of the installer.
To test these changes what was done:
1. A new installer package was built on this branch and published to Azure, with a version of  5.3.7
2. That installer package was downloaded and extracted
3. The package source was modified to remove it only looking for release versions of packages to ensure it would pull a 5.3 version of Sandbox Admin
4. The install was ran, and confirmed that it pulled 5.3.1102 of the Sandbox Admin package, which is the latest for v5.3
And that in the folder where Sandbox Admin was installed, the appsettings.json now contained the tpdm …

ODS-5147 - Add TPDM namespace to sandbox admin install script

---

Scripts/NuGet/EdFi.Installer.SandboxAdmin/Install-EdFiOdsSandboxAdmin.psm1

When building up a connection configuration Hashtable from a connection string during install, Integrated Security was always being set to true, which later on in the install would cause errors when trying to created a user in Postgres. This differed from the WebApi install where Integrated Security would be false unless it was being set to true as part of a parameter passed in as part of the install, so in the shared function Add-SqlLogins (in AppCommon) it would not try to add the logins and instead warn about not being able to create them and then move onto the next part of the install. Now with this change, Sandbox Admin install will act the same as WebApi when integrated security has not been set.
Additionally while testing this, it would found that the Postgres connection strings …

ODS-5149 - Set IntegratedSecurity based on being present in connection string for SandboxAdmin install

---

Application/EdFi.Ods.WebApi/Program.cs
Scripts/NuGet/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1

Note for the reviewer, I've removed log "Loading configuration files" since it doesn't seem to add value; if you consider it necessary, I can bring it back right after Log4net is initialized.

[ODS-5097] Changing the default log location for the Web API running under IIS

---

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj
Application/EdFi.Ods.Api.IntegrationTestHarness/appsettings.json
Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj
Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj
Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj
configuration.packages.json
logistics/scripts/modules/postmanTestHarnessConfiguration.json

This brought in latest from main and updated configuration.packages.json to reference the latest codegen built on net6.
Please note that tests will still be failing as part of this and are covered in ODS-5242. For this you should see CodeGen version 5.4.28 able to be installed and run and that the solution will build.

ODS-5241 - Update to use latest CodeGen for NET6

---

DatabaseTemplate/Scripts/Glendale.ps1
DatabaseTemplate/Scripts/Northridge.ps1

Test with v5.3 or with removal of 1330-UpdateVersionTo54.sql to avoid running into upgrade scenario.

[ODS-5269] Upgrade Glendale and Northridge to v5.3

---

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj
Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj
Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj
Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj

Part of the .NET6 upgrade also updated the Nhibernate package, and once upgraded, there were TypeExceptions being thrown on a number of smoke tests and Repository tests. Downgrading back to the previous version fixes this. Another ticket will be opened to investigate what is needed to get the latest version of NHibernate working.
With ODS-5242 still being under review in PR #383  not all tests will be working on this branch, but if you apply its commits to this branch and do the same for the ODS repo you should see everything working.

ODS-5273 - Downgrade Nhibernate to previous version from before net6 upgrade

---

logistics/scripts/run-tests.ps1

This fixes an issue found where when invoking dotnet test there were errors since with anything past NET5, a reference assembly is put in a ref folder, and then dotnet test was trying to execute against those items, as seen in the screenshot below. This was resolved by filtering out the ref folder.
Please not that other tests will still be failing on this build and will be handled by later tickets.
On feature-net6 branch currently:
On this branch now:

ODS-5242 - Fix Invoke-DotnetTest

---

logistics/scripts/modules/TestHarness.psm1

Previously it was hard coded to pull netcoreapp31 and now instead it will use a wildcard like what is used for finding the TestHarness executable.

ODS-5246 - Update path access for SDK Gen Console

---

Application/EdFi.Ods.SandboxAdmin/Contexts/PostgresIdentityContext.cs
Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj
Application/EdFi.Ods.SandboxAdmin/Startup.cs

[UseHangfireServer got deprecated in favor of AddHangfireServer](https://www.hangfire.io/blog/2021/08/30/hangfire-1.7.25.html), however, there is already a call to _AddHangfireServer_ so the call to _UseHangfireServer_ can be safely removed.

[ODS-5287] Sandbox Admin throws an exception during startup

---

logistics/scripts/modules/config/config-management.psm1

In the powershell script we pull the paths database scripts might be contained in, and the order the paths were pulled in the script is how they would be passed to DbDeploy, and it was ordered as follows before:
Ed-Fi-ODS
Ed-Fi-ODS-Implementation
Ed-Fi-ODS\Application\EdFi.Ods.Standard
Ed-Fi-ODS-Implementation\Plugin
With Implementation being ordered before Standard, if Implementation had scripts in it, such as putting a script in `Ed-Fi-ODS-Implementation\Artifacts\MsSql\Structure\Ods`, then when DbDeploy ran that got executed first and logged in the DeployJournal, and then when Standard scripts were looked at, [this line](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-Databases/blob/main/src/EdFi.Db.Deploy/DatabaseCommands/DeployDatabaseFromPathCommand.cs#L118) in DbDeploy would be …

ODS-5075 - Swap order of scripts paths passed for DbDeploy execution

---

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj
Application/EdFi.Ods.Api.IntegrationTestHarness/Program.cs
Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj
Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj
Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj

Cannot write DateTime with Kind=UTC to PostgreSQL type 'timestamp without time zone', consider using 'timestamp with time zone'. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.
I was getting above error after upgrading to Npgsql package to "6.0.3"  .Basically posgreSQl default to timestamp with time zone  now So I added additional code to make it work like before with  AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
And then it will use timestamp without time zone for ClientAccessToken class - Expiration property for example here
Reference Links
https://stackoverflow.com/questions/70643895/how-to-say-datetime-timestamp-without-time-zone-in-ef-co …

[ODS-5247] Update Npgsql and HealthChecks libraries

---

configuration.packages.json

Note
One of the builds here is currently failing due to a previous merge causing builds to fail on main. Once that is addressed this PR will be updated.

ODS-5184 WebApi Postgres install does not include port number in connection string in appsettings

---

Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj
configuration.packages.json

For this PR, the only changes needed were to update the nuget package reference, and then update to reference the latest CodeGen that was built after FluentValidation was updated in that solution.
Related PRs:
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-Extensions/pull/43
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/477

[ODS-5254] - Update FluentValidation to 10.x

---

configuration.packages.json

FluentMigration was updated as part of ODS-5254, but the extension packages were not rebuilt and referenced as part of that process, so now when trying to call the validators on any of those extensions they would throw an exception.
To test this and confirm the updated packages resolve the issue:
1. Update the appsettings.json in WebApi to reference all three plugins tpdm, sample, and homograph
2. Update configuration.packages.json to reference the old versions from before changes shown here
3. Try to post to Descriptors /tpdm/rubricRatingLevelDescriptors and see that you get the exception reported
4. Try to post to Resources /sample/buses and see that you get the exception reported
5. try to post to Resources /homograph/students and see that you get the exception reported
6. Try to post …

[ODS-5397] - Update extension packages after FluentMigration update

---

Scripts/NuGet/EdFi.Installer.SandboxAdmin/Install-EdFiOdsSandboxAdmin.psm1
Scripts/NuGet/EdFi.Installer.SwaggerUI/Install-EdFiOdsSwaggerUI.psm1
Scripts/NuGet/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1

Before this change, you could specify values for both of the parameters, but SwaggerUI and the API would only get installed to wherever was specified in the WebApplicationPath parameter. Now the installers have been changed so that WebSitePath signifies the base path to the Ed-Fi Website setup in IIS, and then WebApplicationPath will be the subfolder for where each specific application is installed under the Ed-Fi Website. This matches the changes that were done as part of the AdminApp installer as well.
To test this:
1. Make sure you don't already have any EdFi sites setup in IIS.
2. Download the updated installer for WebApi, version 6.0.2 [here](https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.Suite3.Installer.WebApi/6.0.2/overview)
3. Follow the …

[ODS-5112] - Make WebApplicationPath and WebSitePath function as separate parameters

---

.github/workflows/edFi.installer.sandboxAdmin manual.yml
Scripts/NuGet/EdFi.Installer.SandboxAdmin/EdFi.Installer.SandboxAdmin.nuspec
Scripts/NuGet/EdFi.Installer.SandboxAdmin/build-package.ps1

This differs from the previous workflows in two regards:
1. It runs on `windows-latest` instead of `ubuntu-latest` since we have not ported over the necessary Powershell scripts to be compatible with linux. 
2. There is only one workflow that is manually triggered, and not a manually triggered and pull request workflow. This matches how it existed on TeamCity.

[ODS-5402] - Add workflow for Sandbox Admin Installer

---

logistics/scripts/modules/database/postgres-database-management.psm1
logistics/scripts/modules/packaging/nuget-helper.psm1
logistics/scripts/modules/utility/cross-platform.psm1

This adds a new module, **cross-platform.psm1**, with a single function, **Get-IsWindows**,  to test if a machine is Windows without the automatic $IsWindows variable.
With this function, also adds:
- Validation to ensure Mono is installed on Unix-like systems
- Validation to ensure Postgres binaries are installed on Unix-like systems.
This has been tested on PS 5 on windows and PS 7.2 on Unix.

[ODS-5363] Create a PowerShell function that returns whether it's running on Windows

---

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj
Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj
Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj

All that was needed was updating the edfi.suite3.security.dataaccess package since the one being referenced before (6.0.11) was built from a branch and not main, and was from before all of the multiple auth changes were made.

[ODS-5434] - Fix Multiple Auth postman test failures

---

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj
Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj
Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj
logistics/scripts/modules/path-resolver.psm1
logistics/scripts/modules/tools/ToolsHelper.psm1
logistics/scripts/modules/utility/cross-platform.psm1

- Add Get-DotnetRuntimes function that returns current dotnet runtimes in a table
- Update Test-PostgreSQLBinariesInstalled to check if psql command is available
- Update Install-NuGetCli to check if mono command is available
- Update Get-AncestorItemPath to be more unix-friendly, removed searching for windows slashes
- Update Test-DotNetCore to use Get-DotnetRuntimes to test for required dotnet runtimes

[ODS-5362] Use dotnet --list-runtimes to ensure that dotnet is installed

---

.github/workflows/edFi.installer.swaggerUI manual.yml
Scripts/NuGet/EdFi.Installer.SwaggerUI/EdFi.Installer.SwaggerUI.nuspec
Scripts/NuGet/EdFi.Installer.SwaggerUI/build-package.ps1

This runs on Windows-latest like the other installers, until we complete the necessary powershell work to run on linux images.
Like the other installer there is also no pull request workflow, which matches how it existed in TeamCity, since there is no building/testing of code that happens, just building the installer package.
[This PR](https://github.com/Ed-Fi-Alliance/Ed-Fi-TeamCity-Configs/pull/53) to remove the TeamCity config should get approved/merged AFTER this PR is approved and merged.

[ODS-5403] - Add workflow for Swagger UI installer

---

logistics/scripts/Invoke-PostmanIntegrationTests.ps1
logistics/scripts/modules/build-management.psm1

To replace this, a new build step called `Select Node Version` has been created on the two builds that need it [here](https://intedfitools1.msdf.org/buildConfiguration/OdsPlatform_OdsApi_OdsApiInitDevIntegrationTest?mode=builds#all-projects) and [here](https://intedfitools1.msdf.org/buildConfiguration/OdsPlatform_OdsApi_PostgreSQL_OdsApiInitDevIntegrationTest?mode=builds#all-projects).
This is an intermediate step to moving these builds over to Github Actions where we will be able to specify the version of Node to use as part of the action.

[ODS-5367] - Remove function for selecting node version from build script

---

Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1
build.teamcity.ps1
logistics/scripts/Invoke-SdkGen.ps1
logistics/scripts/modules/TestHarness.psm1
logistics/scripts/modules/packaging/create-package.psm1

Now the InitDev builds in TeamCity will run SdkGen and also generate the ApiSdk and TestSdk Packages. To accomplish this, a new build parameter was added `odsapi.build.generateSdkPackages` and when set to true, it will generate the two sdk packages after SdkGen has been run. In TeamCity the initdev builds also had the parameter `odsapi.build.runSdkGen` set to true since that is required for generating these two packages. Currently both initdev builds have this new parameter set to false, and the build.teamcity.ps1 will set this value to false if a value is not pulled from TeamCity.
One thing to note is that SdkGen and GenreateSdkPackages tasks will not be executed as part of initdev for local development, so if you want to test this script locally, you would need to make sure they are set …

[ODS-4931] - Add task to generate ApiSdk and TestSdk as part of integration build

---

Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1
DatabaseTemplate/Modules/create-database-bacpac.psm1
DatabaseTemplate/Modules/database-template-source.psm1
Initialize-PowershellForDevelopment.ps1
logistics/scripts/modules/packaging/nuget-helper.psm1
logistics/scripts/modules/path-resolver.Tests.ps1
logistics/scripts/modules/path-resolver.psm1
logistics/scripts/modules/plugin/plugin-source.Tests.ps1
logistics/scripts/modules/tools/ToolsHelper.psm1
logistics/scripts/modules/utility/hashtable.tests.ps1

Made some changes in order to support Unix. Other files in the script group were modified only if needed by scripts in the script group.
* replaced all paths with forward slashes for unix
* add functions for testing for and Installing SqlPackage in **ToolsHelper.psm1**
* use new Test-SqlPackage function for unix systems in **create-database-bacpac.psm1**
* in **nuget-helper.psm1**
* fix adding to path for unix
* add double quotes for unix pathing 
* Use mono on Unix to run nuget.exe
* only check for blocked files on Windows in **Initialize-PowershellForDevelopment.psm1**
* add Pester tests for 
* path-resolver.psm1
* plugin-source.psm1
* hashtable.psm1 (fixed)
All other files have been imported with no errors at the very least.

[ODS-5370] Support PS 7.2 and Unix - Script group 1

---

configuration.packages.json

This PR has also ODS-5519 Remove Migration Utility references changes

ODS-5516  ODS-5519 Integrate latest 4.0a Data Standard Work as of August 1 & Remove Migration Utility references

---

.github/workflows/InitDev (Postgres), Tests using Sandbox, Year-Specific and Shared Instance.yml
.github/workflows/InitDev (Postgres),Unit tests,Integration tests.yml
.github/workflows/InitDev,Unit tests,Integration tests,Package.yml
.github/workflows/InitDev,Unit tests,Integration tests,Smoke Tests using Sandbox, Year-Specific and Shared Instance.yml
Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1
build.github.ps1
build.teamcity.ps1
logistics/scripts/Invoke-SdkGen.ps1

This resolved the reported issue since what was happening was the testsdk and apisdk were not being generated correctly 
in the right builds, so the testsdk that was generated was just the renamed apisdk that did not contain all the necessary resources in the contained dll. The approach to fix this was to introduce two new parameters for handling the package generation, since we need to be able to generate one or the other, or both. These two new parameters control the logic flow that would allow you to generate them in that same combination.
The new parameters referenced in this PR have been added to the initdev template build [here](https://intedfitools1.msdf.org/admin/editBuildParams.html?id=template:OdsPlatform_OdsApiInitDevUnitTestPackageTemplate) , with both set to false, matching …

ODS-5568 - Create separate parameters for creating apisdk and testsdk packages

---

logistics/scripts/modules/load-path-resolver.ps1
logistics/scripts/modules/packaging/create-package.psm1
logistics/scripts/modules/packaging/restore-packages.psm1

Fixed unix pathing for the following files.
- restore-packages.psm1
- create-package.psm1
- load-path-resolver.ps1
Also check for windows and use mono if not for nuget restore

[ODS-5512] Support PS 7.2 and Unix - Script group 2

---

DatabaseTemplate/Modules/create-database-bacpac.psm1
DatabaseTemplate/Modules/get-populated-from-nuget.ps1
DatabaseTemplate/Modules/get-populated-from-web.ps1
DatabaseTemplate/Modules/get-template-from-web.ps1
logistics/scripts/modules/TestHarness.psm1
logistics/scripts/modules/database/database-management.psm1
logistics/scripts/modules/database/postgres-database-management.psm1
logistics/scripts/modules/packaging/create-package.psm1
logistics/scripts/modules/packaging/nuget-helper.psm1
logistics/scripts/modules/packaging/packaging.psm1
logistics/scripts/modules/packaging/restore-packages.psm1
logistics/scripts/modules/tools/ToolsHelper.psm1
logistics/scripts/modules/utility/cross-platform.psm1
logistics/scripts/modules/utility/xml-validation.psm1
logistics/scripts/run-tests.ps1

Note that no changes were made to `database-management.psm1` since SQL Server for Linux is not going to be supported; PostgreSQL is the only supported engine in Linux.
To test `get-populated-from-nuget.ps1`, you have to use a v2 Nuget feed (v3 isn't supported by Save-Package), use: https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v2/

[ODS-5372] Support PS 7.2 and Unix - Script group 3

---

.github/workflows/InitDev (Postgres), Tests using Sandbox, Year-Specific and Shared Instance.yml
.github/workflows/InitDev (Postgres),Unit tests,Integration tests.yml
.github/workflows/InitDev,Unit tests,Integration tests,Package.yml
.github/workflows/InitDev,Unit tests,Integration tests,Smoke Tests using Sandbox, Year-Specific and Shared Instance.yml

In previous update to move everything to 6.1 we missed changing the minor version. Now it is updated.

ODS-5579 - Update initdev builds for 6.1

---

logistics/scripts/activities/build/create-database-package.ps1

This was disabled in a previous PR since Github Actions runs on Postgres14 which we do not support yet, but with corresponding work [here](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/568) we can re-enable it since we are now running against Postgres13.

ODS-5580 - Re-enable creating postgres backup when making database packages

---

.github/workflows/InitDev (Postgres), Tests using Sandbox, Year-Specific and Shared Instance.yml
.github/workflows/InitDev (Postgres),Unit tests,Integration tests.yml
.github/workflows/InitDev,Unit tests,Integration tests,Package.yml
.github/workflows/InitDev,Unit tests,Integration tests,Smoke Tests using Sandbox, Year-Specific and Shared Instance.yml
build.githubactions.ps1

We figured out there were a few situations that the way we were trying to determine which ODS branch to check out would not always work. Namely in these examples:
- If you created a branch for your work in the ODS repo but had no corresponding work in the Implementation repo, when we would try to check out the ODS repo in the workflow, it could not resolve the correct name, as seen [here](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/actions/runs/3201463853/jobs/5229469442#step:7:1) .So then the ODS would end up staying on main instead of your feature branch
- Using HEAD_REF did not always resolve to the correct value, depending on how the workflow was triggered. In the case of it being triggered by a pull request, then HEAD_REF would correctly resolve to the feature …

ODS-5581 - Update step for checking out ods repo

---

configuration.packages.json

Incorporates code generation fix for Profiles when not including one of the reference involved in a unified key, and a validation logic fix to prevent incorrect failures.

[ODS-5601] Issues to do with Profiles on TEA project

---

Scripts/NuGet/EdFi.RestApi.Databases/Deployment.psm1
Scripts/NuGet/EdFi.RestApi.Databases/prep-package.ps1
logistics/scripts/activities/build/promote-packages.ps1
logistics/scripts/modules/LoadTools.psm1
logistics/scripts/modules/build-management.psm1

Most changes here were simple path fixes, but a few other notable changes were:
- Updating a path to the DbDeploy tool in the .store folder to be lowercase since in Ubuntu it named the folder with all lowercase letters
- Checking for Windows to determine if we use the DbDeploy exe or not in the nuspec file for the Database package we build.
Since this centered around package prep, below is an example of a powershell script I used to test out the RestApi.Database package prep and creation to confirm the scripts worked after updating, and then I compared the package contents to ensure they were matching:
```
& "./Initialize-PowershellForDevelopment.ps1"
$params = @{
DatabaseId = 'EdFi.Suite3.RestApi.Databases'
PackageVersion = '0.0.0'
PackageOutput = './packages'
}
$parameters = @{ …
```

ODS-5375 - Update Script Group 6 to support PS7 and Unix

---

DatabaseTemplate/Modules/create-database-template.psm1
configuration.packages.json

After recent changes, it meant that the Minimal Template Postgres build was not correctly being named with ".PostgreSQL" at the end of the name. The script previously set the nuspec name correctly to include ".PostgreSQL", but the other nuspec properties were not set, so when nuget pack was called, it was not creating the correct package file name based on the id.
To see this issue, if you look at a previous build for the Minimal Postgres template [here](https://intedfitools1.msdf.org/buildConfiguration/OdsPlatform_OdsApi_Packages_EdFiOdsMinimalTemplatePostgreSQL/184422?buildTab=artifacts), you can see on this one how the nuget package is called EdFi.Suite3.Ods.Minimal.Template when it should be called EdFi.Suite3.Ods.Minimal.Template.PostgreSQL. …

ODS-5557 - Fix building of Postgres minimal template

---

DatabaseTemplate/Modules/create-database-template.psm1
DatabaseTemplate/Modules/create-minimal-template.psm1
Scripts/NuGet/EdFi.RestApi.Databases/PostDeploy.ps1
logistics/scripts/run-smoke-tests.ps1

NOTE - the ticket did not call for updated create-minimal-template.ps1.  However, the changes were minor and it allowed for easier testing of the changes to create-database-template.ps1
Changes:
1. Replaced back slashes with forward slashes
2. On non-windows environments removed the .exe extension from executable file name references
3. Replaced OS specific environment variables with cross-platform equivalent references
4. On PostDeploy.ps1 added a parameter of Engine PosgreSQL for non-windows machines
Steps to test:
1. Update line 363 of InitializeDevelopmentEnvironment.psm1, removing the ToLower() function call so the line looks like `"-r", $RespositoryRoot,`)
5. `initdev -Engine PostgreSQL`
6. Checkout tag 4.0.0-a on Ed-Fi-Standard
7. `Initialize-MinimalTemplate -samplePath <root …

[ODS-5376] Support PS 7.2 and Unix - Script group 7

---

.github/workflows/InitDev (Postgres),Unit tests,Integration tests.yml
.github/workflows/InitDev,Unit tests,Integration tests,Package.yml
.github/workflows/InitDev,Unit tests,Integration tests,Smoke Tests using Sandbox, Year-Specific and Shared Instance.yml
logistics/scripts/Invoke-PostmanIntegrationTests.ps1
logistics/scripts/run-tests.ps1

Now the initdev builds that run unit and integration/postman tests have a test reporter step that collects the logs to report on if the tests passed or failed. 
For an example of a build with failing unit tests, there is [this build](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/actions/runs/3292104493/jobs/5427072615) with [this report](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/runs/9015251880) showing failures
And for an example of a build with failing integration tests, there is [this build](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/actions/runs/3299947939/jobs/5443895121) with [this report](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/runs/9037734743) showing failures
To be able to see any of the logs from a …

ODS-5609 - Add test reporting to InitDev builds

---

DatabaseTemplate/Modules/create-database-template.psm1
DatabaseTemplate/Modules/create-minimal-template.psm1
DatabaseTemplate/Modules/create-populated-template.psm1
DatabaseTemplate/Modules/create-tpdm-minimal-template.psm1
DatabaseTemplate/Modules/create-tpdm-template.psm1

This mostly consisted of updating paths to use / instead of \ and fixing one Copy-Item call to use `.Name` to ensure only the name was pulled, since in PS it pulled just the filename but in PWSH it pulled the full name with path.
After these changes, using the modules in PWSH in both Unix and Windows worked.

ODS-5377 - Support PS 7.2 and Unix - Script group 8

---

DatabaseTemplate/Modules/create-database-template.psm1
Initialize-PowershellForDevelopment.ps1
Scripts/NuGet/EdFi.RestApi.Databases/PostDeploy.ps1
Scripts/NuGet/EdFi.RestApi.Databases/prep-package.ps1
logistics/scripts/run-smoke-tests.ps1

Note that the next modified scripts don't belong to this group:
- create-database-template.psm1
- prep-package.ps1
- run-smoke-tests.ps1
... I modified them to call `GetExeExtension` instead of `Get-IsWindows` since it's a bit more readable.

[ODS-5379] Support PS 7.2 and Unix - Script group 10

---

Scripts/NuGet/EdFi.Installer.SandboxAdmin/Install-EdFiOdsSandboxAdmin.psm1
Scripts/NuGet/EdFi.Installer.SandboxAdmin/test.ps1
Scripts/NuGet/EdFi.Installer.SwaggerUI/Install-EdFiOdsSwaggerUI.psm1
Scripts/NuGet/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1
Scripts/NuGet/EdFi.Installer.WebApi/test.ps1

IIS management only accepts paths that use backslash as directory separator, so I'm reverting a few changes that were made in https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/pull/548.

[ODS-5381] Ensure that all PowerShell scripts use forward slashes as directory separator

---

DatabaseTemplate/Modules/database-template-source.psm1
DatabaseTemplate/Scripts/Glendale.ps1
DatabaseTemplate/Scripts/Northridge.ps1
logistics/scripts/modules/database/database-lifecycle.psm1

The links for restoring Glendale and Northridge have now been updated to ODS 6.0 backups for SQL Server. Additionally, initdev workflow was tested with the Postgres backups and issues were found where it did not work so code changes were made to get them to work. Now both versions should be able to be restored successfully and have the API/Sandbox run against them.
One thing to note if running with these larger datasets and you try to create a new database via Sandbox Admin, it will take some time to create a new database since these datasets are much larger. There is also a known issue where there are less students seen in the database in Postgres, and we have created ODS-5666 to address this.

ODS-5643 - Update Glendale and Northridge to 6.0 and allow for Postgres restoring

---

Application/EdFi.Ods.Api.IntegrationTestHarness/log4net.config
Application/EdFi.Ods.WebApi/log4net.config
Application/EdFi.Ods.WebApi/log4net.development.config

In order to enable this functionality, both logger RequestResponseDetailsLogger and appender RequestResponseDetailsFileAppender must be configured, if one or both are missing, request-response details will not be logged.
request-response details log example:
`2022-12-19 19:07:26,445 [.NET ThreadPool Worker] ERROR 
ClientId: 2 
{ RequestURL = http://localhost:54746/data/v3/ed-fi/assessments, RequestMethod = Post, ResponseCode = 400, ResponseMessage = Unable to resolve value 'uri://ed-fi.org/AssessmentCategoryDescriptor#Benchmark test2' to an existing 'AssessmentCategoryDescriptor' resource. } 
EdFi.Ods.Common.Exceptions.BadRequestException: Unable to resolve value 'uri://ed-fi.org/AssessmentCategoryDescriptor#Benchmark test2' to an existing 'AssessmentCategoryDescriptor' resource.
at …

[ODS-5675] Include basic Request-Response details in the logs

---

Scripts/NuGet/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1
configuration.packages.json

Tested on Powershell 5.1.19041.2364 and 7.2.8 following instructions on https://techdocs.ed-fi.org/display/ODSAPIS3V53/Getting+Started+-+Binary+Installation

[ODS-5660] Remove dependency on WebAdministration module in IIS installers

---

DatabaseTemplate/Scripts/GlendalePostgreSql.ps1
DatabaseTemplate/Scripts/NorthridgePostgreSql.ps1

Test this code change in 6.1 Tag
From the 6.1 tag branch 
Manually update this function in this file https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/main/DatabaseTemplate/Modules/database-template-source.psm1
function Get-TemplateBackupPath {
[CmdletBinding()] param(
[parameter(ValueFromPipeline)]
[string]$backupFolder = $databaseTemplateDatabaseFolder,
[parameter(ValueFromPipeline)]
[string]$engine
)
if (-not (Test-Path $backupFolder)) { return }
if($engine -eq "PostgreSQL"){
return (Get-ChildItem $backupFolder -File -Filter "*.sql" | Select-Object -First 1 -Expand FullName)
} else {
return (Get-ChildItem $backupFolder -File -Filter "*.bak" | Select-Object -First 1 -Expand FullName)
}
}
Add PR 2 files in 6.1 tag branch 
Refer …

ODS-5667 Glendale and Northridge PG 6.1 Migration

---

Scripts/NuGet/EdFi.Installer.WebApi/Install-EdFiOdsWebApi.psm1

When install type is Sandbox, 
- By default, ApiSettings.PlainTextSecrets is set to true.
- If WebApiFeatures includes parameter PlainTextSecrets, will take that value, ex.
```
$parameters = @{
PackageVersion = "6.1.901"
DbConnectionInfo = @{
Engine="SqlServer"
Server="localhost"
UseIntegratedSecurity=$true
}
WebApiFeatures = @{
PlainTextSecrets=$false
}
InstallType = "Sandbox"
}
```
Use package EdFi.Suite3.Installer.WebApi 7.0.4 to test

[ODS-4956] Sandbox 5.2 latest is encrypting the Secret after first use

---

DatabaseTemplate/Modules/database-template-source.psm1
DatabaseTemplate/Modules/get-template-from-web.ps1

- Will not download previously downloaded archived files
- Fixed issue where "7Zip4Powershell" was not being installed correctly
- Downloaded archive files are unpacked to a folder, not directly to Databases folder
Note: Use branch https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/tree/ODS-5708_6.1test to test

[ODS-5708] Northridge as Populated Template is not always taking valid backup path for Reset-PopulatedTemplate

---

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj
Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj
Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj
Application/EdFi.Ods.WebApi/appsettings.json

To test, run the following script against EdFi_Admin db
```
-- For MSSQL
INSERT INTO dbo.Profiles 
SELECT 'Sample-Profile-DB-Resource-ExcludeOnly',
'<Profile name="Sample-Profile-DB-Resource-ExcludeOnly">
<Resource name="School">
<ReadContentType memberSelection="ExcludeOnly">
<Property name="NameOfInstitution" />
<Property name="OperationalStatusDescriptor" />
<Property name="CharterApprovalSchoolYearTypeReference" />
<Property name="SchoolTypeDescriptor" />
<Property name="AdministrativeFundingControlDescriptor" />
<Collection name="EducationOrganizationAddresses" memberSelection="IncludeAll" />
<Collection name="SchoolCategories" memberSelection="IncludeAll" />
</ReadContentType>
<WriteContentType memberSelection="ExcludeOnly">
<Property name="ShortNameOfInstitution" />
<Property …
```

[ODS-5612] Add support for reading API Profile definitions from the EdFi_Admin database

---

Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1
build.github.ps1
build.teamcity.ps1

all 8 Database Templates in ODS repo  ( example :Pkg EdFi.Ods.Minimal.Template) needs ODS Implementation repo which executes Ed-Fi-ODS-Implementation/Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1
internally invokes Invoke-RebuildSolution to build the Ed-Fi-ODS solution which has projects in both repos . As we are implementation caching here once Cache Nuget packages  is created based all cs projects and configuration.packages.json , then it should call restore based on Ed-Fi-ODS solution to use cached nuget package from github actions repository cache storage ,so we are passing --no-restore https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/pull/623/files#diff-7769734a8c2fbe0fefe7c68401741c0dcad90200f40e8746ec0caed409eea398R283 at the time building the …

[ODS-5741] Nuget package caching enabled in Github Actions builds of Ed-Fi-ODS repo

---

Application/EdFi.Ods.Api.IntegrationTestHarness/appsettings.json

Enabled Profiles feature on integration test harness.

[ODS-5764] Profile usage is not enforced (v5.1)

---

.github/workflows/Cleanup Caches by a branch.yml
.github/workflows/CodeQL Security Scan.yml
.github/workflows/InitDev (Postgres), Tests using Sandbox, Year-Specific and Shared Instance.yml
.github/workflows/InitDev (Postgres),Unit tests,Integration tests.yml
.github/workflows/InitDev,Unit tests,Integration tests,Package.yml
.github/workflows/InitDev,Unit tests,Integration tests,Smoke Tests using Sandbox, Year-Specific and Shared Instance.yml
Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1
build.githubactions.ps1
logistics/scripts/Invoke-PostmanIntegrationTests.ps1
logistics/scripts/Invoke-SdkGen.ps1

In general, it's not recommended to share the NuGet package cache across operating systems. NuGet packages may include platform-specific binaries or dependencies, and they may not work correctly on different operating systems.
Note that if you use the same cache key for multiple operating systems, you should make sure that the NuGet packages are compatible with all operating systems. Some packages may include platform-specific binaries or dependencies, and they may not work correctly on different operating systems. In that case, you should use separate cache keys for each operating system to ensure that the packages are only used on compatible systems. That's the reason we have 2 caches in this ODS Implementation Repo

[ODS-5742] Nuget package caching enabled in Github Actions builds of Ed-Fi-ODS-Implementation repo

---

configuration.packages.json

All the below packages are NOT AVAILABLE in Azure Artifacts now , so generated database template packages in this PR 
"PackageName": "EdFi.Suite3.Ods.Extensions.Homograph",     "PackageVersion": "5.3.31"
"PackageName": "EdFi.Suite3.Ods.Profiles.Sample",       "PackageVersion": "5.3.15",
"PackageName": "EdFi.Suite3.Ods.Extensions.Sample",      "PackageVersion": "5.3.35",
"PackageName": "EdFi.Suite3.Ods.Minimal.Template",      "PackageVersion": "5.3.309",
"PackageName": "EdFi.Suite3.Ods.Populated.Template",     "PackageVersion": "5.3.345",
"PackageName": "EdFi.Suite3.Ods.Minimal.Template.PostgreSQL",     "PackageVersion": "5.3.281",
"PackageName": "EdFi.Suite3.Ods.Populated.Template.PostgreSQL",      "PackageVersion": "5.3.295",
"PackageName": "EdFi.Suite3.Ods.Minimal.Template.TPDM.Core", …

[ODS-5776] code fix for re-generate missing packages and merging  to f-Change-Queries-Enhancements-v5.3

---

Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1
DatabaseTemplate/Modules/create-database-template.psm1
DatabaseTemplate/Modules/create-minimal-template.psm1
DatabaseTemplate/Modules/create-populated-template.psm1
DatabaseTemplate/Modules/database-template-source.psm1
configuration.packages.json
logistics/scripts/modules/database/database-lifecycle.psm1
logistics/scripts/modules/tools/ToolsHelper.psm1

To test the database packages are loaded correctly, run initdev without the tpdm plugin, this should load minimal and populated templates for the specified database engine

[ODS-5766] Add the Standard version to the minimal and populated templates

---

Application/EdFi.Ods.Api.IntegrationTestHarness/log4net.config
Application/EdFi.Ods.WebApi/log4net.config
Application/EdFi.Ods.WebApi/log4net.development.config

Include any profiles header (content-type header starting with "application/vnd.ed-fi." ) sent by an API client in the RequestResponseDetails log messages. The field is left blank in the log message if the client does not provide a profiles header in the request.
Example of log message including a profiles header:
`2023-04-19 19:19:16,898 [64] INFO  ClientId:43 RequestUrl:http://localhost:8765/data/v3/ed-fi/schools RequestMethod:POST ProfilesHeader:application/vnd.ed-fi.school.Test-Profile-Resource-WriteOnly.writable+json ResponseCode:403 ResponseMessage:Forbidden`

[ODS-5794] Enhance Request-Response logging with profile header information

---

Application/SolutionScripts/InitializeDevelopmentEnvironment.psm1

This change allows to run invoke-codegen without standard and extension version params, using the default values
Fixes
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-Extensions/actions/runs/4760223779/jobs/8460328494
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/actions/runs/4760111221/jobs/8460095416
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/actions/runs/4760204619/jobs/8460290085

[ODS-5813] Fix CodeQL builds

---

Application/EdFi.Ods.Api.IntegrationTestHarness/UpdateAdminDatabaseTask.cs

This allows the Postman test collection to correctly execute when the ODS runs either data standard 4.0.0 or 5.0.0. It functions be providing Postman environmental variables (in environment.json file generated by the TestHarnes. These new variables can be templated into Postman requests requiring data standard specific. 
The assertions allowing 404 responses on endpoints impacted Parent -> Contact change have also been removed from the Postman collections. This was a temporary measure and is no longer required after this update to the Postman collections.

[ODS-5921] Postman test coverage for Contacts (after renamed from Parent in the standard)

---

logistics/scripts/run-tests.ps1

This command update enables display of failing tests at the console, whether run locally or in GitHub Actions.

[ODS-6065] Improved test execution logging

---

logistics/scripts/modules/database/postgres-database-management.psm1

PowerShell 7.4 was recently released. The breaking feature that was introduced in 7.3 was kept for 7.4
Since 7.4 is LTS, in the near future, github runner images may be upgraded to PS 7.4, so this fix was tested on versions 7.3, 7.4, and 5.1

[ODS-6161] Fix bug on Postgres-database-management.psm1

---

.github/workflows/InitDev, Smoke Tests.yml
.github/workflows/InitDev, Unit tests, Integration tests, Package.yml
.github/workflows/PostgreSQL.Binaries manual .yml

github.run_number  will be different in each developer's fork Hence So package number is getting in minus number ,so added new step to reset  to 1 if gets minus for BUILD_INCREMENTER ,so that it will work in Fork also

[ODS-6083] Setup Ed-Fi-ODS-Implementation in Developer's Fork

---

.github/workflows/Docker Test.yml
Docker/build-images.ps1
Docker/get-versions.ps1
Docker/ods-api-bulk-load-console/alpine/Dockerfile
Docker/ods-api-bulk-load-console/alpine/README.md
Docker/ods-api-bulk-load-console/alpine/log4net.template.config
Docker/ods-api-bulk-load-console/alpine/run.sh

Image edfialliance/ods-api-bulk-load-console runs on .NET 8. Can be used as a CLI command and needs to have mounted at least the data folder pointing /var/bulkLoad/data
To test
1. Build image locally, using powershell. BulkLoad 7.2.6 was built using .NET 8
```powershell
cd Docker/ods-api-bulk-load-console/alpine
$BulkLoadVersion='7.2.6'
docker build . -t edfialliance/ods-api-bulk-load-console --build-arg BULKLOAD_VERSION=$BulkLoadVersion
```
2. Run image to verify (---help parameter is default, so this command should display a list of available options for the Bulk Load Client)
```powershell
docker run -it --rm edfialliance/ods-api-bulk-load-console
```
3. Download Sample XML Files from [here](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-Standard/tree/v5.0.0/Samples/Sample%20XML)
4. Setup …

[ODS-5443] Client Side Bulk Loader in a Container

---

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj
Application/EdFi.Ods.SandboxAdmin/EdFi.Ods.SandboxAdmin.csproj
Application/EdFi.Ods.WebApi/EdFi.Ods.WebApi.csproj

I tried with 8.0.3  it was throwing
Error	CS1929	'IHostBuilder' does not contain a definition for 'ConfigureLogging' and the best extension method overload 'WebHostBuilderExtensions.ConfigureLogging(IWebHostBuilder, Action<ILoggingBuilder>)' requires a receiver of type 'Microsoft.AspNetCore.Hosting.IWebHostBuilder'	
So I updated to 7.07 another patch version for this issue

[ODS-6389] Update npgsql package - v7.1

---

Application/Ed-Fi-Ods.sln
logistics/scripts/modules/settings/settings-management.psm1

- Updated `Ed-Fi-Ods.sln` to include the new `EdFi.Security.DataAccess.IntegrationTests` project.
- Added an entry in the PowerShell configuration management module so that the appsettings.json in `EdFi.Security.DataAccess.IntegrationTests` is updated during initdev processes.

[ODS-6216] Add EF Core DbContexts and supporting code to EdFi.Security.DataAccess (5.x)

---

Application/EdFi.Ods.SwaggerUI/Resources/Swashbuckle_index.html

This fixes a bug introduced in the first set of changes for ODS-6410. The bug prevents the SwaggerUI authentication dialog from opening if tenant or route context value selections are not available.

[ODS-6410] Fix - Swagger UI v7.2 is not updating Token URL

---

.github/workflows/Rebuild Database Templates.yml
build.githubactions.ps1
configuration.packages.json

Below is a structured breakdown of each use case:
Use Case 1:
Scenario:
A new commit occurs in one of the three repositories (Ed-Fi-ODS, Ed-Fi-ODS-Implementation, or Ed-Fi-Extensions).
The workflow begins by updating the CodeGen package but fails before completing.
Expected Behavior:
In the first run, the workflow updates the CodeGen package version. However, the workflow fails after this update, preventing the completion of other package updates.
Example Workflow Run:
[Failed after updating CodeGen package](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/actions/runs/10517476403/job/29141657598).
Use Case 2:
Scenario:
The workflow is re-triggered after the failure in Use Case 1.
It should skip the CodeGen package update since it was already updated and continue updating …

[ODS-6434]Rebuild Database Templates build -Skip already successful package creation from working branch

---

DatabaseTemplate/Scripts/Northridge.ps1
Docker/ods-api-bulk-load-console/alpine/Dockerfile

Testing Steps
Check out 7.2 Tag in your local as branch for ODS & ODS Implementation Branch
Update code in this ticket PR
Update ApiSettings:PopulatedTemplateScript" "Northridge" as below
C:\Ed-Fi-ODS-Implementation\Application\EdFi.Ods.WebApi> dotnet user-secrets set "ApiSettings:PopulatedTemplateScript" "Northridge"
4 . In a PowerShell session navigate to \Ed-Fi-ODS-Implementation.
Execute .\Initialize-PowershellForDevelopment.ps1.
5 . Run  InitDev  
6 . Install-DbDeploy
7 . Execute Reset-PopulatedTemplate.
Finally verify in database for record count and Northridge ISD
SELECT * from EdFi_Ods_Populated_Template.edfi.Student
SELECT * from EdFi_Ods_Populated_Template.edfi.EducationOrganization
SELECT count from EdFi_Ods_Populated_Template.edfi.Student
SELECT count from …

[ODS-6472] Northridge SQL Server 7.2 Migration

---

.github/workflows/Analyze docker images.yml

https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/actions/runs/10799344881

[ODS-6479] Analyze Docker Images updated

---

LandingPage/index.css
LandingPage/index.html
LandingPage/index.js

Changes included in this PR:
- Changed the probing logic to test against a pre-defined set of version ranges.
- Removed the need to specify the API variants (shared-instance, year-specific, ...) for each API version in the configuration.
- Replaced Materialize with the latest version of Bootstrap.
- Removed the logic related to displaying patch versions and suites.

[ODS-6496] Update Landing Page

---

Application/EdFi.Ods.Features.OwnershipBasedAuthorization/Security/OwnershipInitializationCreateEntityDecorator.cs

The main focus of this refactoring was to apply SOLID and DRY principles to the existing authorization code to make it easier to understand and (more importantly) unit testable. The previous code made use of many bits of contextual information through the execution path for authorization. This branch introduces a `DataManagementAuthorizationPlan` class (built using the new `IDataManagementAuthorizationPlanFactory`) that consolidates the gathering of all this contextual information in one place, and as late as possible in the authorization processing. The result is the removal of many "context" dependencies from many classes.
A second focus decomposes two large classes into testable units: `AuthorizationBasisMetadataSelector` and `EntityAuthorizer`. These two classes had way too many …

[ODS-6510] Apply SOLID and DRY principles to security/authorization logic (through consolidation of common code)

---

.github/workflows/Docker Test.yml
.github/workflows/Publish to Azure Artifacts.yml
.github/workflows/Publish to Docker Hub.yml

Increased the delay between checks because it seems we're reaching GitHub API rate limits.

[ODS-6577] Increase delay between checks

---

Application/EdFi.Ods.Api.IntegrationTestHarness/EdFi.Ods.Api.IntegrationTestHarness.csproj
Application/EdFi.Ods.Api.IntegrationTestHarness/Migrations/ISecurityDatabaseConnectionStringCatalog.cs
Application/EdFi.Ods.Api.IntegrationTestHarness/Migrations/MultiTenantSecurityDatabaseConnectionStringCatalog.cs
Application/EdFi.Ods.Api.IntegrationTestHarness/UpdateAdminDatabaseTask.cs

[[ODS-6481] Update package and github action versions (#1108) are set up for different tenants (#1209)](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/commit/f688905ca6d2cd77fcb21e296451d9c145de2818)
[ODS-6481]: https://edfi.atlassian.net/browse/ODS-6481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ODS-6615] API only allows tenant1's profiles when different profiles are set up for different tenants

---

InstallerPackages/EdFi.RestApi.Databases/Deployment.psm1
InstallerPackages/EdFi.RestApi.Databases/prep-package.ps1
logistics/scripts/modules/packaging/create-package.psm1
logistics/scripts/modules/tools/ToolsHelper.psm1

builds are updated to run on ubuntu instead of windows. This now packs the DbDeploy package for Linux env. and doesn’t work in Windows. So It requires this code change  .  Currently now database PowerShell Installer to pack dbDeploy .nupkg instead of executable 
Tested with EdFi.Suite3.RestApi.Databases.Standard.5.0.0.7.1.3892

[ODS-6709]  EdFi.Suite3.RestApi.Databases Binary Installation CodeFix

---

logistics/scripts/modules/postmanTestHarnessConfiguration.json

Modify API client initialization to avoid using API client with 3000+ EdOrgIds for anything but testing.

[ODS-6694] Optimize Get Partitions Query
